blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/Prageethcs/hippocamp/discussions
    about: For questions, ideas, or open-ended discussion (please don't file these as issues).
